"""Fixed the Models.PY

Revision ID: 553c9d03df6d
Revises: d7140b846360
Create Date: 2023-04-17 17:06:39.595625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553c9d03df6d'
down_revision = 'd7140b846360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
